# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test Workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing Dependencies
        run: npm i
      - name: Debug env
        run: |
          echo "NODE_ENV=" ${{env.DB_DRIVER}}
      - name: Run Tests
        env:
          DB_DRIVER: ${{env.DB_DRIVER}}
          DB_CONNECTION: ${{env.DB_CONNECTION}}
          DB_NAME: ${{env.DB_NAME}}
          QUEUE_DRIVER: ${{env.QUEUE_DRIVER}}
          QUEUE_CONNECTION: ${{env.QUEUE_CONNECTION}}
          QUEUE_TENANT_CONNECTION: ${{env.QUEUE_TENANT_CONNECTION}}
        run: npm test
